insta_combined/accounts/urls.py
from django.urls import path
# from django.contrib.auth.views import LoginView, LogoutView
# from .views import signup
from . import views
app_name='accounts'

urlpatterns=[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

insta_combined/insta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')), #빈칸이 이쓰면 include로 보내라.
]

insta_combined/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


# class User_info(AbstractUser):

#     gender = models.CharField(max_length=30)  # True for male and False for female
#     age=models.IntegerField()

# class Account(models.Model):
#     username = models.CharField(max_length = 20)
#     password = models.CharField(max_length = 50)
#     # age = models.IntegerField()
#     # gender = models.CharField(max_length=10)
#     created_at = models.DateTimeField(auto_now_add = True,null=True,blank=True)

insta_combined/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class SignUpForm(forms.ModelForm):

    password = forms.CharField(label = 'Password', widget = forms.PasswordInput)
    Repeat_password = forms.CharField(label = 'Repeat_password', widget = forms.PasswordInput)
  
    class Meta:
        model = User
        fields = ['username', 'password', 'age', 'gender']

    def clean_Repeat_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['Repeat_password']:
            raise forms.ValidationError('비밀번호 불일치')
        return cd['Repeat_password']

insta_combined/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
# from .forms import SignUpForm
from django.contrib import auth
# from .models import Account
from datetime import datetime

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'], password=request.POST['password1'],
                    first_name=request.POST['last_name'],last_name=request.POST['first_name'],email=request.POST['email'])
            
            auth.login(request, user)
            return render(request, 'accounts/signup_complete.html')
        return render(request, 'accounts/signup.html')

    return render(request, 'accounts/signup.html')

def login(request):
    if request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username = username, password = password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'photo/home.html')
        else:
            return render(request, 'accounts/login.html', {'error': 'us or apssis not coree'})
    else:
        return render(request, 'accounts/login.html')
def logout(request):
    auth.logout(request)
    return render(request, 'photo/home.html')


# def signup(request):
#     if request.method == 'POST':
#         signup_form = SignUpForm(request.POST)
        
#         if signup_form.is_valid():
#             user_instance = signup_form.save(commit=False)
#             user_instance.set_password(signup_form.cleaned_data['password'])
#             user_instance.save()
#             return render(request, 'accounts/signup_complete.html', {'username':user_instance.username})
#     else:
#         signup_form = SignUpForm()

#     return render(request, 'accounts/signup.html', {'form':signup_form.as_p})

insta_combined/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<!-- <div class='row'>
    <div class='col'></div>
    <div class='col-6'>
        <div class='alert alert-primary' role='alert'>
            로그인 정보 입력</div>
        <form action='' method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit' value='login' class='btn btn-primary'>
        </form>
    </div>
    <div class='col'></div>
</div> -->
<div class='container'>
    <h1>login</h1>
    <form method='POST' action=''>
        {% csrf_token %}
        유저네임
        <input name='username' type='text'>
        비번
        <input name='password' type='password'>
        <input type='submit' class= 'btn btn-primary' value='로그인'>
    </form>
</div>
{% endblock %}

insta_combined/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col'></div>
    <div class='col-6'>
        <div class='alert alert-primary' role='alert'>
          로그아웃 됨
        </div>
        <a href="{% url 'accounts:login' %}" class='btn btn-outline-success'> login하기</a>
    </div>
    <div class='col'></div>
</div>
{% endblock %}

insta_combined/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<!-- <div class='row'>
    <div class='col'></div>
    <div class='col-6'>
        <form action='' method='post'>
            <div class='alert alert-info'>로그인 정보입력</div>
            {% csrf_token %}
            <label>Username : <input type='text' name = 'Username'></label>
            <label>Password : <input type='password' name = 'password'></label>
            <label>Repeat Password : <input type='password' name = 'password2'></label>        </form>
            <input type = 'submit' value='Sign up' class='btn btn-outline-info'>
        </form>
        </div>
    <div class='col'></div>
</div> -->
<div class='continer'>
    <h1>sign up!</h1>

    <form method='POST' action ="">
        {% csrf_token %}
        아이디 &emsp;&emsp;&emsp;&nbsp;
        <input name='username' type ='text'>
        <br>
        비밀번호 &emsp;&emsp;&nbsp;
        <input name='password1' type='password'>
        <br>
        비밀번호확인 &nbsp;
        <input name='password2' type = 'password'>
        <br>
        이름 &emsp;&emsp;&emsp;&emsp;&nbsp;
        <input name='last_name' type = 'text'>
        <br>
        성별: &emsp;&emsp;&emsp;&emsp;&nbsp;&emsp;
        <input type='radio' name='first_name'value='남' checked>남성
        <input type='radio' name='first_name'value='여' >여성
        <br>
        이메일 주소 &emsp;
        <input name='email' type = 'text'>
        <br>
      
        <input type = 'submit' class='btn btn-primary' value='sign up'>
    </form>
</div>
{% endblock %}

insta_combined/accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col'></div>
    <div class='col-6'>
        <div class='alert alert-primary' role='alert'>성공적 회원가입</div>
        <a href ="{% url 'accounts:login' %}">로그인으로 이동></a>
        </div>
    <div class='col'></div>
</div>
{% endblock %}