insta_combined/insta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')), #빈칸이 이쓰면 include로 보내라.
]

insta_combined/photo/urls.py
from django.urls import path
from .views import PhotoCreate, PhotoDelete, PhotoList, PhotoDetail, PhotoUpdate 
from photo.views import webcam_test, mic_test, home, index, room


app_name= 'photo'
urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),# as view를 붙여야 generic이용가능
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    # path('/main/',main,name='detail'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),
    path('', PhotoList.as_view(), name='index'),
    path('webcam_test/', webcam_test),
    path('mic_test/',mic_test),
    path('home/', home),
    path('index/',index),
    path('index/<str:room_name>/', room, name='room')
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta_combined/photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    # video = models.ImageField(blank=True, upload_to= 'timeline_photo/%Y/%m/%d')#d알아서 날짜 추가.
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')#d알아서 날짜 추가.
    created = models.DateTimeField(auto_now_add=True)#지금시간 생성
    updated = models.DateTimeField(auto_now=True)#한번 업데이트
    
    def __str__(self):
        return "text : " +self.text
    
    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

class Eve(models.Model):
    # student = models.ForeignKey(User, on_delete = models.CASCADE, related_name='user')
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    number = models.IntegerField()
    result = models.IntegerField()
    state = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)

class Threshold(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    open_ear=models.FloatField()
    close_ear=models.FloatField()
    ear_thresh=models.FloatField()  
    created_at=models.DateTimeField(auto_now=True)

insta_combined/photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo,Eve
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User


########## 눈인식을 위한 코드 from azurr
from scipy.spatial import distance as dist
from imutils.video import VideoStream
from imutils import face_utils
from threading import Thread
from threading import Timer

###
import numpy as np
import cv2
from azure.cognitiveservices.vision.face import FaceClient
from msrest.authentication import CognitiveServicesCredentials
from scipy.spatial import distance as dist

####
import imutils
import time
import timeit
import matplotlib.pyplot as plt
from . import make_train_data as mtd
from . import light_remover as lr
from . import ringing_alarm as alarm
import face_recognition
import matplotlib.pyplot as plt
from sklearn import metrics
import pygame
import threading

from .models import Eve
from .models import Threshold
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib import auth


def eye_aspect_ratio(eye) :
    A = dist.euclidean(eye[1], eye[5])
    B = dist.euclidean(eye[2], eye[4])
    C = dist.euclidean(eye[0], eye[3])
    ear = (A + B) / (2.0 * C)
    return ear

def init_open_ear() :
    time.sleep(5)
    print("open init time sleep")
    ear_list1 = []
    th_message1 = Thread(target = init_message)
    th_message1.daemon = True
    th_message1.start()
    print("Hi1")
    for i in range(7) :
    	print("Hi2")
    	ear_list1.append(both_ear)
    	time.sleep(1)
    global OPEN_EAR
    OPEN_EAR = sum(ear_list1) / len(ear_list1)
    print("open list =", ear_list1, "\nOPEN_EAR =", OPEN_EAR, "\n")

def init_close_ear() : 
    time.sleep(2)
    th_open.join()
    time.sleep(5)
    print("close init time sleep")
    ear_list2 = []
    th_message2 = Thread(target = init_message)
    th_message2.daemon = True
    th_message2.start()
    time.sleep(1)
    for i in range(7) :
        ear_list2.append(both_ear)
        time.sleep(1)
    global CLOSE_EAR
    CLOSE_EAR = sum(ear_list2) / len(ear_list2)
    global EAR_THRESH
    EAR_THRESH = (((OPEN_EAR - CLOSE_EAR) / 2) + CLOSE_EAR) #EAR_THRESH means 50% of the being opened eyes state
    print("close list =", ear_list2, "\nCLOSE_EAR =", CLOSE_EAR, "\n")
    print("The last EAR_THRESH's value :",EAR_THRESH, "\n")


def init_message():
    print("init_message")
    print("졸음인식시작!")
    alarm.sound_alarm("C:\\Users\\InKunAhn\\Documents\\GitHub\\CapstoneLMS\\sound\\init_sound.mp3")


# 코드 잠수확인용
def printForTest():
	print("코드 진행중입니다.")


def testForThreshold():
    KEY = 'e58722bb0e8e4bd9bcd627343c3e421f'
    ENDPOINT = 'https://recogface.cognitiveservices.azure.com/'
    face_client = FaceClient(ENDPOINT, CognitiveServicesCredentials(KEY))
    img_name = 'C:\\Users\\InKunAhn\\Documents\\GitHub\\CapstoneLMS\\identification\\inkun.jpg'
    image_data = open(img_name,'rb')
    detected_faces = face_client.face.detect_with_stream(image=image_data, recognition_model="recognition_02",)

    if not detected_faces:
        raise Exception('No face detected from image {}'.format(img_name))

    # Display the detected face ID in the first single-face image.
    # Face IDs are used for comparison to faces (their IDs) detected in other images.

    print('Detected face ID from', img_name, ':')
    for face in detected_faces: print (face.face_id)
    person1Id=face.face_id
    print()

    # Save this ID for use in Find Similar
    first_image_face_ID = detected_faces[0].face_id    
    
    #22222
    print("이제 시작한다!")

	#1.
    global EAR_THRESH  #Threashold value
    EAR_THRESH = 0

	#2.
	#It doesn't matter what you use instead of a consecutive frame to check out drowsiness state. (ex. timer)
    EAR_CONSEC_FRAMES = 20 
    COUNTER = 0 #Frames counter.

	#3.
    closed_eyes_time = [] #The time eyes were being offed.
    TIMER_FLAG = False #Flag to activate 'start_closing' variable, which measures the eyes closing time.
    ALARM_FLAG = False #Flag to check if alarm has ever been triggered.

	#4. 
    ALARM_COUNT = 0 #Number of times the total alarm rang.
    RUNNING_TIME = 0 #Variable to prevent alarm going off continuously.

	#5.    
    PREV_TERM = 0 #Variable to measure the time eyes were being opened until the alarm rang.

	#6. make trained data 
    np.random.seed(9)
    power, normal, short = mtd.start(25) #actually this three values aren't used now. (if you use this, you can do the plotting)
	#The array the actual test data is placed.
    test_data = []
	#The array the actual labeld data of test data is placed.
    result_data = []

    print("?")

    print("Hi4")

	#9.
    global th_open
    th_open = Thread(target = init_open_ear)
    print("Hi5")
    th_open.daemon = True
    th_open.start()
    global th_close
    th_close = Thread(target = init_close_ear)
    th_close.daemon = True
    th_close.start()
    
    #cv2.VideoCapture(0)에서 웹캠이 하나면 0을 이고 2개이상일 경우, 0,1,2...으로 웹캠을 설정할 수 있다.
    video_capture = cv2.VideoCapture(0)   
    count =0
  
    while th_close.is_alive():

        global frame
        ret, frame = video_capture.read()
        if th_open.is_alive():
            cv2.putText(frame, "Open your both eyes until the sound end", (10,100), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,0,255), 2)
        if (th_close.is_alive())&(th_open.is_alive()==False):
            cv2.putText(frame, "Close your both eyes until the sound end", (10,100), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255,0,0), 2)   
        #L, gray = lr.light_removing(frame)
        if(int(video_capture.get(1)) % 1 == 0):
            cv2.imwrite("C:\\Users\\InKunAhn\\Documents\\GitHub\\CapstoneLMS\\frame\\%d.jpg" % count, frame)
            # print('Saved frame%d.jpg' % count)
            image_data1 = open("C:\\Users\\InKunAhn\\Documents\\GitHub\\CapstoneLMS\\frame\\%d.jpg" % count,'rb')
            detected_faces2 = face_client.face.detect_with_stream(image=image_data1,return_face_landmarks=True, recognition_model="recognition_02", )
            count += 1	
            person2Id=0
            if len(detected_faces2)==0:
                cv2.putText(frame, "Don't leave from Mornitor", (30,100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)   
            
            else:
                
                for face in detected_faces2: 
                    person2Id=face.face_id
                    (x,y)=(face.face_landmarks.eye_left_bottom.x,face.face_landmarks.eye_left_bottom.y)
                    (x1,y1)=(face.face_landmarks.eye_left_inner.x,face.face_landmarks.eye_left_inner.y)
                    (x2,y2)=(face.face_landmarks.eye_left_outer.x,face.face_landmarks.eye_left_outer.y)
                    (x3,y3)=(face.face_landmarks.eye_left_top.x,face.face_landmarks.eye_left_top.y)
                    leftEye=dist.euclidean((x,y),(x3,y3))/dist.euclidean((x1,y1),(x2,y2))
                    (x4,y4)=(face.face_landmarks.eye_right_bottom.x,face.face_landmarks.eye_right_bottom.y)
                    (x5,y5)=(face.face_landmarks.eye_right_inner.x,face.face_landmarks.eye_right_inner.y)
                    (x6,y6)=(face.face_landmarks.eye_right_outer.x,face.face_landmarks.eye_right_outer.y)
                    (x7,y7)=(face.face_landmarks.eye_right_top.x,face.face_landmarks.eye_right_top.y)
                    rightEye=dist.euclidean((x4,y4),(x7,y7))/dist.euclidean((x5,y5),(x6,y6))
                    global both_ear
                    both_ear=(leftEye+rightEye)*500
                    leftEyeShape=np.array([[x,y],[x1,y1],[x2,y2],[x3,y3]],dtype=np.int32)
                    rightEyeShape=np.array([[x4,y4],[x5,y5],[x6,y6],[x7,y7]],dtype=np.int32)
                    leftEyeHull = cv2.convexHull(leftEyeShape)
                    rightEyeHull = cv2.convexHull(rightEyeShape)
                    cv2.drawContours(frame, [leftEyeHull], -1, (0,255,0), 1)
                    cv2.drawContours(frame, [rightEyeHull], -1, (0,255,0), 1)
                    # print (face.face_id)

            
                    result1=face_client.face.verify_face_to_face(person1Id, person2Id, person_group_id=None, 
                                                large_person_group_id=None, custom_headers=None, raw=False)
                    # print(result1.is_identical,result1.confidence)

                
                    if(result1.is_identical==False):

                        cv2.putText(frame, "Who are you?", (30,100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)


                    print("Present both eyes value : ",both_ear)

        cv2.imshow('Frame',frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    video_capture.release()
    cv2.destroyAllWindows()
    
    Threshold_instance=Threshold(open_ear=OPEN_EAR,close_ear=CLOSE_EAR, ear_thresh=EAR_THRESH, created_at=datetime.now(), user_id=id_user)
    Threshold_instance.save()

    # Threshold.objects.create(open_ear=OPEN_EAR,close_ear=CLOSE_EAR
    # ,ear_thresh=EAR_THRESH, created_at=datetime.now(), student_id=user.id)
    
    print("테스트완료")

    

# Create your views here.
def drowsiness():
    KEY = 'e58722bb0e8e4bd9bcd627343c3e421f'
    ENDPOINT = 'https://recogface.cognitiveservices.azure.com/'
    face_client = FaceClient(ENDPOINT, CognitiveServicesCredentials(KEY))
    img_name = 'C:\\Users\\InKunAhn\\Documents\\GitHub\\CapstoneLMS\\identification\\inkun.jpg'
    image_data = open(img_name,'rb')
    detected_faces = face_client.face.detect_with_stream(image=image_data, recognition_model="recognition_02",)

    if not detected_faces:
        raise Exception('No face detected from image {}'.format(img_name))

    # Display the detected face ID in the first single-face image.
    # Face IDs are used for comparison to faces (their IDs) detected in other images.

    print('Detected face ID from', img_name, ':')

insta_combined/photo/templates/photo/home.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="get">
    <input type='submit' class = 'button' value='Take photo for Face' name='face_photo'>
  </form>
{% endblock %}

insta_combined/photo/templates/photo/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>

<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
    
    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/index/' + roomName + '/';
        };
    </script>
</body>
</html>

insta_combined/photo/templates/photo/mic_test.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}

<style>
* {
  font-family: Verdana, Arial, sans-serif;
}
a:link {
  color:#000;
  text-decoration: none;
}
a:visited {
  color:#000;
}
a:hover {
  color:#33F;
}
.button {
  background: -webkit-linear-gradient(top,#008dfd 0,#0370ea 100%);
  border: 1px solid #076bd2;
  border-radius: 3px;
  color: #fff;
  display: none;
  font-size: 13px;
  font-weight: bold;
  line-height: 1.3;
  padding: 8px 25px;
  text-align: center;
  text-shadow: 1px 1px 1px #076bd2;
  letter-spacing: normal;
}
.center {
  padding: 10px;
  text-align: center;
}
.final {
  color: black;
  padding-right: 3px; 
}
.interim {
  color: gray;
}
.info {
  font-size: 14px;
  text-align: center;
  color: #777;
  display: none;
}
.right {
  float: right;
}
.sidebyside {
  display: inline-block;
  width: 45%;e
  min-height: 40px;
  text-align: left;
  vertical-align: top;
}
#headline {
  font-size: 40px;
  font-weight: 300;
}
#info {
  font-size: 20px;
  text-align: center;
  color: #777;
  visibility: hidden;
}
#results {
  font-size: 14px;
  font-weight: bold;
  border: 1px solid #ddd;
  padding: 15px;
  text-align: left;
  min-height: 150px;
}
#start_button {
  border: 0;
  background-color:transparent;
  padding: 0;
}


/* 마이크 */
</style>
<h1 class="center" id="headline">  Web Speech API Demonstration</h1>
<div id="info">
<p id="info_start">Click on the microphone icon and begin speaking.</p>
<p id="info_speak_now">Speak now.</p>
<p id="info_no_speech">No speech was detected. You may need to adjust your
  <a href="//support.google.com/chrome/bin/answer.py?hl=en&amp;answer=1407892">
    microphone settings</a>.</p>
<p id="info_no_microphone" style="display:none">
  No microphone was found. Ensure that a microphone is installed and that
  <a href="//support.google.com/chrome/bin/answer.py?hl=en&amp;answer=1407892">
  microphone settings</a> are configured correctly.</p>
<p id="info_allow">Click the "Allow" button above to enable your microphone.</p>
<p id="info_denied">Permission to use microphone was denied.</p>
<p id="info_blocked">Permission to use microphone is blocked. To change,
  go to chrome://settings/contentExceptions#media-stream</p>
<p id="info_upgrade">Web Speech API is not supported by this browser.
   Upgrade to <a href="//www.google.com/chrome">Chrome</a>
   version 25 or later.</p>
</div>
<div class="right">
<button id="start_button" onclick="startButton(event)">
  <img id="start_img" src="C:\Users\InKunAhn\djangoPractice\insta_combined\layout\mic.gif" alt="Start"></button>
</div>
<div id="results">
<span id="final_span" class="final"></span>
<span id="interim_span" class="interim"></span>
<p>
</div>
<div class="center">
<p>
<div id="div_language">
  <select id="select_language" onchange="updateCountry()"></select>
  &nbsp;&nbsp;
  <select id="select_dialect"></select>
</div>
</div>
<script>
var langs =
[['English', ['en-US', 'United States'],
           ['en-GB', 'United Kingdom']],
['한국어',   ['ko-KR']]];

for (var i = 0; i < langs.length; i++) {
select_language.options[i] = new Option(langs[i][0], i);
}
select_language.selectedIndex = 0;
updateCountry();
select_dialect.selectedIndex = 0;
showInfo('info_start');

function updateCountry() {
for (var i = select_dialect.options.length - 1; i >= 0; i--) {
  select_dialect.remove(i);
}
var list = langs[select_language.selectedIndex];
for (var i = 1; i < list.length; i++) {
  select_dialect.options.add(new Option(list[i][1], list[i][0]));
}
select_dialect.style.visibility = list[1].length == 1 ? 'hidden' : 'visible';
}

var final_transcript = '';
var recognizing = false;
var ignore_onend;
var start_timestamp;
if (!('webkitSpeechRecognition' in window)) {
upgrade();
} else {
start_button.style.display = 'inline-block';
var recognition = new webkitSpeechRecognition();
recognition.continuous = true;
recognition.interimResults = true;

recognition.onstart = function() {
  recognizing = true;
  showInfo('info_speak_now');
  start_img.src = 'C:\\Users\\InKunAhn\\djangoPractice\\insta_combined\\layout\\mic-animate.jpg';
};

recognition.onerror = function(event) {
  if (event.error == 'no-speech') {
    start_img.src = 'C:\\Users\\InKunAhn\\djangoPractice\\insta_combined\\layout\\mic-animate.jpg';
    showInfo('info_no_speech');
    ignore_onend = true;
  }
  if (event.error == 'audio-capture') {
    start_img.src = 'C:\\Users\\InKunAhn\\djangoPractice\\insta_combined\\layout\\mic.jpg';
    showInfo('info_no_microphone');
    ignore_onend = true;
  }
  if (event.error == 'not-allowed') {
    if (event.timeStamp - start_timestamp < 100) {
      showInfo('info_blocked');
    } else {
      showInfo('info_denied');
    }
    ignore_onend = true;
  }
};

recognition.onend = function() {
  recognizing = false;
  if (ignore_onend) {
    return;
  }
  start_img.src = 'C:\\Users\\InKunAhn\\djangoPractice\\insta_combined\\layout\\mic.jpg';
  if (!final_transcript) {
    showInfo('info_start');
    return;
  }
  showInfo('');
  if (window.getSelection) {
    window.getSelection().removeAllRanges();
    var range = document.createRange();
    range.selectNode(document.getElementById('final_span'));
    window.getSelection().addRange(range);
  }
};

recognition.onresult = function(event) {
  var interim_transcript = '';
  for (var i = event.resultIndex; i < event.results.length; ++i) {
    if (event.results[i].isFinal) {
      final_transcript += event.results[i][0].transcript;
    } else {
      interim_transcript += event.results[i][0].transcript;
    }
  }
  final_transcript = capitalize(final_transcript);
  final_span.innerHTML = linebreak(final_transcript);
  interim_span.innerHTML = linebreak(interim_transcript);
  if (final_transcript || interim_transcript) {
    showButtons('inline-block');
  }
};
}

function upgrade() {
start_button.style.visibility = 'hidden';
showInfo('info_upgrade');
}

var two_line = /\n\n/g;
var one_line = /\n/g;
function linebreak(s) {
return s.replace(two_line, '<p></p>').replace(one_line, '<br>');
}

var first_char = /\S/;
function capitalize(s) {
return s.replace(first_char, function(m) { return m.toUpperCase(); });
}



function startButton(event) {
if (recognizing) {
  recognition.stop();
  return;
}
final_transcript = '';
recognition.lang = select_dialect.value;
recognition.start();
ignore_onend = false;
final_span.innerHTML = '';
interim_span.innerHTML = '';
start_img.src = 'C:\\Users\\InKunAhn\\djangoPractice\\insta_combined\\layout\\mic-slash.jpg';
showInfo('info_allow');
showButtons('none');
start_timestamp = event.timeStamp;
}

function showInfo(s) {
if (s) {
  for (var child = info.firstChild; child; child = child.nextSibling) {
    if (child.style) {
      child.style.display = child.id == s ? 'inline' : 'none';
    }
  }
  info.style.visibility = 'visible';
} else {
  info.style.visibility = 'hidden';
}
}

var current_style;
function showButtons(style) {
if (style == current_style) {
  return;
}
current_style = style;
copy_button.style.display = style;
copy_info.style.display = 'none';
}
</script>

{% endblock %}

insta_combined/photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class='row'>
    <div class='col'></div>
    <div class='col-12 col-xl-8 col-md-8'>
        <div class='alert alert-primary' role='alert'>
            모든 부분을 채워주세요.
        </div>
        <form action='' method='post' enctype='multipart/form-data'>
            <!-- html의 폼형태에서 입력할 때는 모두 text 파일로 인지 따라서 form 옆에 이게 image 파일이라는 것을 알려줄 수 있도록 해야함 -->
            {% csrf_token %}

            {{form.as_p}}
            <input type='submit' value='Upload' class='btn btn-primary'>
        </form>
    </div>
    <div class='col'></div>
</div>




{% endblock %}

insta_combined/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<!-- 진짜 지울건지 확인. form 또 보여줄 피룡없음 -->
<div class='alert alert-primpary' role='alert'>
    진짜로 {{object}}를 지우실 건가요?
</div>
<form action='' method='post'>
    {% csrf_token %}
    <input type='submit' value='Delete OK'>
</form>
{% endblock %}

insta_combined/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<!-- <div class='row'>
    <div class='col'></div>
    <div class='col-12 col-xl-4 col-md-4'>
        <div class='card' style='width: 30rem;'>
            <img src='{{ object.image.url}}' class='card-img-top' alt='...'>
            <div class='card-body'>
                <h5 class='card-title'>{{ object.author }}</h5>
                <p class='card-text'> {{ object.text }}</p>
            </div> 
            <ul class='list-group list-group-flush'>
                <li class='list-group-item'> 생성일 : {{ object.created }}</li>
                <li class='list-group-item'> 수정일 : {{ object.updated }}</li>
            </ul>
            <div class='card-body'>
                <a href="{% url 'photo:update' object.id %}" class='card-link'>수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class='card-link'>삭제하기</a>
            </div>    
        </div>
    </div>
    <div class='col'></div>

</div> -->  
<iframe width="560" height="315" src="https://www.youtube.com/embed/ezbJwaLmOeM" 
                        frameborder="0" 
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
                        allowfullscreen>
            </iframe>	

<center>
<div id="divPosition">

    <form action="" method="get">

        <input type='submit' class = 'button' value ='눈인식 시작' name='btn'>
    </form>

    <!-- <form action="videos/" method="POST">
        {% csrf_token %}

        <button type='submit' class='moveBtn'>이동</button>
    </form> -->
    
</div>
</center>

{% endblock %}

insta_combined/photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class='container'>
    <div class='row'>
        <div class='col'></div>
        <div class='col-5'>
            {% for object in object_list %}
        
        <div class='card'>
            <div class='card-header'>
            {{ object.author }}
            <!-- 모델에서 생성된 포토 -->
        </div>
        <img src='{{ object.image.url}}' class='card-img-top' alt='...' border="0" width="200" height="200">
        <div class='card-body'>
            <p class='card-text'> {{ object.text }}</p>
        </div> 
        <ul class='list-group list-group-flush'>

            <li class='list-group-item'> 생성일 : {{ object.created }}</li>
            <!-- <li class='list-group-item'> 생성일 : {{ object.updated }}</li> -->
        </ul>
        
        <div class='card-body'>
            <a href="{% url 'photo:detail' object.id %}" class='card-link'>영상보기</a>
            <a href="{% url 'photo:update' object.id %}" class='card-link'>수정하기</a>
            <a href="{% url 'photo:delete' object.id %}" class='card-link'>삭제하기</a>
            
        </div>    
        </div>
        {% endfor %}
    </div>
    <div class='col'></div>
</div>
</div>
{% endblock %}

insta_combined/photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class='row'>
    <div class='col'></div>
    <div class='col-12 col-xl-8 col-md-8'>
        <form action='' method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit' value='Create'>
        </form>
    </div>
    <div class='col'></div>
</div>
{% endblock %}

insta_combined/photo/templates/photo/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>

<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>

<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/index/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>

</html>

insta_combined/photo/templates/photo/webcam_test.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}



<form action="" method="get">
  <input type='submit' class = 'button' value='Strat Test' name='eye_test'>
</form>

{% endblock %}