insta_combined/bookmark/urls.py
from django.urls import path
from .views import BookmarkList, BookmarkCreate, BookmarkDelete, BookmarkDetail, BookmarkUpdate

app_name = 'bookmark'

urlpatterns = [
    path('create/', BookmarkCreate.as_view(), name = 'create'),
    path('delete/<int:pk>', BookmarkDelete.as_view(), name = 'delete'), #pk 특정값 가져오기
    path('update/<int:pk>', BookmarkUpdate.as_view(), name = 'update'),
    path('detail/<int:pk>', BookmarkDetail.as_view(), name = 'detail'),
    path('', BookmarkList.as_view(), name = 'index'),
]

insta_combined/insta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('admin/', admin.site.urls),
    path('', include('photo.urls')), #빈칸이 이쓰면 include로 보내라.
]

insta_combined/bookmark/models.py
from django.db import models

class Bookmark(models.Model):
    site_name = models.CharField(max_length=30)
    url = models.URLField()
    contents = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Site name : "+self.site_name+". URL : "+self.url
        
    class Meta:
        ordering = ["-created"]

insta_combined/bookmark/views.py
from django.shortcuts import render

from .models import Bookmark

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView

class BookmarkList(ListView):
    model = Bookmark

class BookmarkCreate(CreateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_create'
    # tempate_name = 'bookmark/temlates/bookmark/'해도됨
    success_url = '/bookmark/' #메인화면으로 돌아간다.
class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_update'
    success_url = '/bookmark/'

class BookmarkDelete(DeleteView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_delete'
    success_url = '/bookmark/'

class BookmarkDetail(DetailView):
    model = Bookmark
    template_name_suffix = '_detail'
    success_url = '/'

insta_combined/bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            자세히 설명해 주세요
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value ="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

insta_combined/bookmark/templates/bookmark/bookmark_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="alert alert-primary" role="alert">
    진짜로 {{object.site_name}}를 지우실 건가요ㅑ?
</div>
<form action="" method="post">
    {% csrf_token%}
    <input type ="submit" value="Delete OK">
</form>
{% endblock %}

insta_combined/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block content %}
<div class = "row">
    <div class = "col"></div>
    <div class="col-12 col-xl-8 cod-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{object.site_name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{object.url}}"></a>{{object.url}}</h6>
                <p class="card-text">{{object.contents }}</p>
                <a href="{% url 'bookmark:update' object.id  %}" class="car-link">수정</a>
                <a href="{% url 'bookmark:delete' object.id  %}" class="car-link">삭제</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

insta_combined/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block content %}
<div class = "row">
    <div class = "col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <!-- #분할 크기 설정 -->
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">게시자 이름</th>
        <th scope="col">사이트명</th>
        <th scope="col">제목</th>
        <th scope="col">수정</th>
        <th scope="col">삭제</th>
      </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
      <tr>
        <td>{{ object.id }}</td>>
        <td><a href="{% url 'bookmark:detail' object.id  %}">{{ object.site_name }}</a></td>
        <td><a href = "{{ object.url }}">{{ object.url }}</a></td>
        <td><a href="{% url 'bookmark:update' object.id  %}">수정</a>
        <td><a href="{% url 'bookmark:delete' object.id  %}">삭제</a></td>
      </tr>
      {% endfor %}

      <a href="{% url 'bookmark:create' %}" class="btn btn-primary">게시글 올리기</a>
    </tbody>
</table>
</div>
<div class="col"></div>
</div>
{% endblock %}

insta_combined/bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block content %}
<div class = "row">
    <div class = "col"></div>
    <div class="col-12 col-xl-8 cod-md-4">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type ="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}